### ISSUE TITLE
Funziona ancora?

### ISSUE THREAD

**Issue by Yoddikko** [Blu-Tiger/streamingcommunity-unofficialapi#1]
Ciao, vorrei sapere se funziona ancora. Perchè nel caso potrei provare a farlo usando Swift e potrei farci un app per iPhone.

**Comment by Blu-Tiger** [comment]
> Ciao, vorrei sapere se funziona ancora. Perchè nel caso potrei provare a farlo usando Swift e potrei farci un app per iPhone.

Dovrebbe funzionare, ma non ho ancora trovato il modo per estrarre il link per il download

**Comment by Yoddikko** [comment]
Mentre lo streaming funziona?

**Comment by Blu-Tiger** [comment]
> Mentre lo streaming funziona?

Ho appena verificato e a quanto pare non funziona, probabilmente qualcosa è cambiato nel sito, il codice è da aggiornare

**Comment by Blu-Tiger** [comment]
> Mentre lo streaming funziona?

L'api restituisce l'url della pagina dello stream, ma non l'url diretto del video.
Ma credo sia possibile caricare la pagina come iframe.

**Comment by Yoddikko** [comment]
Sono quasi riuscito a fare lo stesso codice su Swift, se riesci a prendere anche il link sarebbe perfetto. Se faccio una repo comunque cito il tuo progetto perchè ho copiato pari pari ma trasformandolo in Swift (grazie chatGPT eheh)

**Comment by Blu-Tiger** [comment]
> Se faccio una repo comunque cito il tuo progetto

Ne sarei grato, spero ti sia stato d'aiuto. Per quanto riguarda il link diretto, dovrò fare un po' di reverse engineering ma forse un giorno lo farò.

**Comment by Blu-Tiger** [comment]
Ho creato un plugin per yt-dlp che estrae il link della playlist m3u8 contenente le varie versioni e sottotitoli del video estratto, lo puoi trovare [qui.](https://github.com/Blu-Tiger/StreamingCommunity-yt-dlp-plugin)
