### ISSUE TITLE
Correlazione serietv/stagioni/episodi

### ISSUE THREAD

**Issue by edenazord** [Blu-Tiger/streamingcommunity-unofficialapi#3]
Trovare un metodo per correlare serietv alle stagioni e di conseguenza agli episodi per aumentare le informazioni qualora un utente cercasse una serietv.

**Comment by Blu-Tiger** [comment]
Non so cosa tu intenda precisamente  ma ci sono 2 funzioni principali:
- search(): fa la ricerca e restituisce le informazioni su ogni risultato:
  - id
  - slug
  - nome
  - tipo (tv o movie)
  - score
  - se è  sub o dub
  - last air date
  - numero stagioni
  - immagini e info su di esse
  - url della pagina

- load(): restituisce nome, url, tipo e lista di informazioni su ogni singolo episodio

**Comment by Blu-Tiger** [comment]
Ho aggiunto gli esempi di output delle serie nel README.md
