### ISSUE TITLE
Info

### ISSUE THREAD

**Issue by Arrowar** [Blu-Tiger/streamingcommunity-unofficialapi#4]
Ciao anchio ho inziiato un progetto simile al tuo e volevo chiederti, da dove ti eri estratto, come calcolare il token e l'expire per la vecchia funzione. E se eri riuscito a farlo funzionare.

**Comment by Blu-Tiger** [comment]
Piuttosto che calcolare il token, ho preso l'html grezzo restituito dal sito e ho estratto i vari parametri per ricostruire il link, puoi controllare nel codice la funzione  get_link() che restituisce sia il link iframe incorporabile che il link diretto per il download, se ricordo bene si trattava di una playlist m3u.

Questa è la funzione:
https://github.com/Blu-Tiger/streamingcommunity-unofficialapi/blob/main/scuapi%2Fscuapi.py#L296-L339

Nel caso tu sia interessato solo al download, se ti può interessare avevo già creato un plugin per yt-dlp:
https://github.com/Blu-Tiger/StreamingCommunity-yt-dlp-plugin

**Comment by Arrowar** [comment]
Si certo, ma c'è modo ora di calcolarsi il token come una volta o è troppo offuscato il sito ?

**Comment by Arrowar** [comment]
> Piuttosto che calcolare il token, ho preso l'html grezzo restituito dal sito e ho estratto i vari parametri per ricostruire il link, puoi controllare nel codice la funzione get_link() che restituisce sia il link iframe incorporabile che il link diretto per il download, se ricordo bene si trattava di una playlist m3u.
> 
> Questa è la funzione: https://github.com/Blu-Tiger/streamingcommunity-unofficialapi/blob/main/scuapi%2Fscuapi.py#L296-L339
> 
> Nel caso tu sia interessato solo al download, se ti può interessare avevo già creato un plugin per yt-dlp: https://github.com/Blu-Tiger/StreamingCommunity-yt-dlp-plugin

Ho preferito riscrivere da 0 il downloader, yt dlp andava lento.

**Comment by Blu-Tiger** [comment]
> Si certo, ma c'è modo ora di calcolarsi il token come una volta o è troppo offuscato il sito ? 

Probabilmente sì, magari estraendo un paio di token da dispositivi diversi e confrontandoli o trovando la funzione stessa che li crea si riesce a calcolarlo, lunico poplema è che il calcolo o alcune delle variabili potrebbero cambiare e poi dovresti ri estrarre la nuova funzione con i pararmetri per ricostruirla ogni volta che cambiano il sito

**Comment by Arrowar** [comment]
Si certo era solo per prova, per caso sai dov'è la funzione che crea i parametri ?

**Comment by Blu-Tiger** [comment]
Guardando dalle opzioni sviluppatore del browser puoi vedere da dove viene generata la pagina html contenente il token e da li trovare la funzione in uno del file js se viene creata a lato client se no toccerebbe ricrearla confrontando vari token generati, però probabilmente la funzione in sé è la stessa vecchia, l'unica cosa che cambia probabilmente è la costatante usata per generarlo

**Comment by Arrowar** [comment]
Teoricamente dovrebebe essere questa,ma non riesco a trovare il generatore dei token: https://vixcloud.co/build/assets/streamingcommunity.aca65bf6.js, percaso sai il link giusto ?

**Comment by Blu-Tiger** [comment]
Credo che quello sia per creare il player in se, per quanto riguarda i url credo che sia questo o almeno sembrano esserci funzioni riguardanti dei token: https://vixcloud.co/jwplayer-8.26.2/provider.hlsjs.js

**Comment by Arrowar** [comment]
Va bene grazie mille.

**Comment by Blu-Tiger** [comment]
Ho delle novità, sembra che anche i link con solo la data di scadenza funzionino.

**Comment by Arrowar** [comment]
> Ho delle novità, sembra che anche i link con solo la data di scadenza funzionino.

Sempre con type = video ?

**Comment by Blu-Tiger** [comment]
Sì

**Comment by Arrowar** [comment]
Okay per caso sei i riuscito a scaricare qualcosa a velocità normali senza usare proxy o essere obbligato a mettere 2 thread in parallelo?

**Comment by Blu-Tiger** [comment]
Non ho una connessione veloce, quindi non sono riuscito a fare test di velocità affidabili

**Comment by Arrowar** [comment]
Han okay va bene, grazie lo stesso.

**Comment by Arrowar** [comment]
> Ho delle novità, sembra che anche i link con solo la data di scadenza funzionino.

allora si funziona però i segmenti ts poi danno error 403.

**Comment by Arrowar** [comment]
> Credo che quello sia per creare il player in se, per quanto riguarda i url credo che sia questo o almeno sembrano esserci funzioni riguardanti dei token: https://vixcloud.co/jwplayer-8.26.2/provider.hlsjs.js

Si però sembrebbe essere gestito da terzi la creazione del token infatti sulle ultime righe compare una chiave privata.

**Comment by Blu-Tiger** [comment]
Avevo previsto che potesse essere fatto a lato server, motivo per cui ho optato per l'estrazione dei token direttamente dal html restituito dalle varie api.

**Comment by Blu-Tiger** [comment]
> allora si funziona però i segmenti ts poi danno error 403.

Avranno cambiato dinuovo qualcosa, quando l'avevo testato con yt-dlp funzionava, forse è cambiato qualcosa nel api del cloud provider

**Comment by Arrowar** [comment]
> > allora si funziona però i segmenti ts poi danno error 403.
> 
> Avranno cambiato dinuovo qualcosa, quando l'avevo testato con yt-dlp funzionava, forse è cambiato qualcosa nel api del cloud provider
> 

Si molto probabile infatti ora senza token e expire non funziona più.

**Comment by Arrowar** [comment]
> Avevo previsto che potesse essere fatto a lato server, motivo per cui ho optato per l'estrazione dei token direttamente dal html restituito dalle varie api.

Quello si però peccato.

**Comment by Arrowar** [comment]
Se vuoi unisciti anche te al mio discord così almeno possiamo scriverci più facilmente.

**Comment by Blu-Tiger** [comment]
> Se vuoi unisciti anche te al mio discord così almeno possiamo scriverci più facilmente.

Volentieri, dove posso trovarlo?

**Comment by Arrowar** [comment]
> > Se vuoi unisciti anche te al mio discord così almeno possiamo scriverci più facilmente.
> 
> Volentieri, dove posso trovarlo?

Vai sulla prima repo che ho fatto e sul readme c'è il link.
