### ISSUE TITLE
Doppio parametro token nell'URL della playlist con conseguente errore 403

### ISSUE THREAD

**Issue by RedSquirrel87** [Blu-Tiger/streamingcommunity-unofficialapi#6]
Stavo provando un po' questa libreria nel realizzare un'app per Kodi e funziona tutto alla perfezione se non fosse che al momento di generare l'URL della playlist da passare a Kodi ottengo un URL con doppio parametro token che mi causa un errore 403 quando poi Kodi prova ad accedervi. 
Ad esempio usando un semplice:
`iframe, m3u8_playlist = sc.get_links(watch_url)`

per **m3u8_playlist** ottengo il seguente valore:
`https://vixcloud.co/playlist/263769?b=1?token=6c53e82a405aefe3ce0e61f1e81a1cf0&token=6c53e82a405aefe3ce0e61f1e81a1cf0&expires=1733774265`

Probabilmente è solo un problema da niente a livello di generazione dell'URL, perché eliminando uno dei due parametri token identici poi il link funziona bene quindi non ci sono problemi nei dati ma solo nell'URL 👍

**Comment by Blu-Tiger** [comment]
Effettivamente l url restituito non dovrebbe avere alcun parametro token in quanto sembrano essere obsoleti, ci darò un'occhiata.

**Comment by Blu-Tiger** [comment]
Ho fatta la modifica, ti basta aggiornare il pacchetto, poi dimmi se ci sono altri problemi.

**Comment by RedSquirrel87** [comment]
Confermo che è tutto perfetto adesso, grazie 👍
