### ISSUE TITLE
Problema nell'avvio

### ISSUE THREAD

**Issue by giusedm** [Blu-Tiger/streamingcommunity-unofficialapi#7]
Sto testando questa API e provando un semplice script d'esempio non restituisce nessun errore ma nemmeno un eventuale lista o metadati come dovrebbe fare per adesso il dominio è .computer

**Comment by Blu-Tiger** [comment]
Quindi nell'esecuzione di una cosa simile:
```python
from scuapi import API

sc = API('streamingcommunity.esempio')
test = sc.search('John Wick')
print(test)
```

non ti restituisce niente?

**Comment by giusedm** [comment]
MI da un errore 

    iframe, m3u8_playlist = get_links('https://StreamingCommunity.computer/watch/7540?e=50636')
                            ^^^^^^^^^
NameError: name 'get_links' is not defined

**Comment by giusedm** [comment]
ok tutto risolto era un mio problema dii configurazione, funziona tutto ottimo lavoro!!

**Comment by Blu-Tiger** [comment]
ah si probabimente mancava `sc.`, credo di essermi dimenticato di metterlo nelle documentazione.
