### ISSUE TITLE
Errore get_link

### ISSUE THREAD

**Issue by giusedm** [Blu-Tiger/streamingcommunity-unofficialapi#8]
da questo errore quando si prova a fare un test

scuapi.py", line 319, in get_links
    iframe = _wbpage_as_text(info['props']['embedUrl'])
                             ~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'embedUrl'

**Comment by Blu-Tiger** [comment]
Assicurati di aver inserito il link dell'episodio o diretto del film correttamente, dovrebbe finire con `/watch/` e un numero, tipo:
```python
sc.get_links("https://sc.esempio/watch/6")
```
