### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by SRK7Kyros** [Blu-Tiger/streamingcommunity-unofficialapi#9]
### Traceback:
```
Traceback (most recent call last):
  File "d:\Code\streaming-community\download.py", line 264, in <module>
    asyncio.run(main())
  File "C:\Users\Giulio\scoop\apps\python310\current\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Giulio\scoop\apps\python310\current\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "d:\Code\streaming-community\download.py", line 255, in main
    res = sc.load(url)
  File "C:\Users\Giulio\scoop\apps\python310\current\lib\site-packages\scuapi\scuapi.py", line 144, in load
    r"url\((.*)\)", soup.find("div", class_="title-container")["style"]
TypeError: 'NoneType' object is not subscriptable
```

Ho controllato che il link fosse giusto svariate volte, ipotizzo che sia cambiata la struttura del sito e quindi non riesca più a trovare l'elemento. 
Riusciresti a metterci mano? Ho provato a guardare il `scuapi.py` alla linea 144, ma non sapendo cosa cerca il programma non saprei come cambiarlo (cosa si intende per "poster"?)
![{1E294521-9857-416B-B908-E74C3F34965F}](https://github.com/user-attachments/assets/3b657cd0-1f9b-4520-88a7-27b70230151f)

**Comment by Blu-Tiger** [comment]
Ci guarderò appena possibile

**Comment by Blu-Tiger** [comment]
> cosa si intende per "poster"?

Dovrebbe essere l'immagine poster del contenuto

**Comment by SRK7Kyros** [comment]
nel codice tu cerchi l'immagine poster direttamente sulla pagina web... non sarebbe più semplice sfruttare il filename che ti da l'api, considerando che le url del cdn sono molto prevedibili? 
es. 
![{F27D9178-A353-470A-97DE-D740E085CBC1}](https://github.com/user-attachments/assets/10fa7ab1-84cb-4efc-a643-f17d8b3d6890)
![{682B87AE-860F-4D03-A996-258C277755C5}](https://github.com/user-attachments/assets/9c7e4715-56ba-475f-b0bc-b7c49d356207)
```python
import requests as r

url = 'https://streamingcommunity.family/titles/9155-ti-presento-i-miei'
cdn = 'https://cdn.streamingcommunity.family/images'
sc_id = url.rsplit(r"/", 1)[1].split('-')[0]
res = r.post(f'https://streamingcommunity.family/api/titles/preview/{sc_id}')
images = res.json()["images"]
poster = [i["filename"] for i in images if i["type"] == "poster"][0]
poster_url = f'{cdn}/{poster}'
print(poster_url)

# https://cdn.streamingcommunity.family/images/815bc6f7-1fd5-44cd-8b37-65d9ed39c142.webp
```

**Comment by SRK7Kyros** [comment]
ho sistemato il file, non sono sicuro di aver fatto bene la pull request (è la prima contribution che faccio), spero vada bene. https://github.com/Blu-Tiger/streamingcommunity-unofficialapi/pull/10

**Comment by SRK7Kyros** [comment]
con questi cambiamenti ora la parte di competenza dell'api funziona a norma, nonostante poi crashi l'extractor per yt dlp.

**Comment by Blu-Tiger** [comment]
> ho sistemato il file, non sono sicuro di aver fatto bene la pull request (è la prima contribution che faccio), spero vada bene. https://github.com/Blu-Tiger/streamingcommunity-unofficialapi/pull/10

Grazie del contributo ci darò un'occhiata, sembra possa andare

**Comment by Blu-Tiger** [comment]
> con questi cambiamenti ora la parte di competenza dell'api funziona a norma, nonostante poi crashi l'extractor per yt dlp.

Se stai parlando del plugin per yt-dlp è una repo a parte con delle differenze nel codice, se ti ha dato dei problemi puoi segnalarlo sull'altra repo, così ne tengo traccia più facilmente

**Comment by SRK7Kyros** [comment]
> Grazie del contributo ci darò un'occhiata, sembra possa andare

perfetto.

> > con questi cambiamenti ora la parte di competenza dell'api funziona a norma, nonostante poi crashi l'extractor per yt dlp.
> 
> Se stai parlando del plugin per yt-dlp è una repo a parte con delle differenze nel codice, se ti ha dato dei problemi puoi segnalarlo sull'altra repo, così ne tengo traccia più facilmente

approfondirò domani, sta sera ahimé non riesco.
posso accennare che era un 403 forbidden, ma comunque domani farò un issue come si deve.
